#!/usr/bin/env bash
function getip() {
	ret=`ifconfig $@ | awk '/inet / {print $2}'`
	if [ "$ret" != "127.0.0.1" ] && [ "$ret" != "" ]; then
		echo $ret
	fi
}
for net in /sys/class/net/*
do
	inter=$(basename "$net")
	getip "$inter"
done